api_platform:
    title: API Technical Test Backend Developer Profile
    version: 1.0.0
    description: |
        This a as part of the recruitment process, you are required to complete a small technical test
        to showcase how you tackle a basic programming task.
        You may also be interested by [the GraphQL entrypoint](/api/graphql), [the GraphiQL entrypoint](/api/docs/graphiql)
        and [the GraphQL Playground entrypoint](/api/docs/graphql_playground)
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld: ['application/ld+json']
        jsonhal: ['application/hal+json']
        jsonapi: ['application/vnd.api+json']
        json: ['application/json']
        xml: ['application/xml', 'text/xml']
        yaml: ['application/x-yaml']
        csv: ['text/csv']
        html: ['text/html']
        graphql: ['application/graphql']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3, 2]
        api_keys:
    graphql:
        # Choose between graphiql or graphql-playground
        default_ide: graphql-playground
